### ISSUE TITLE
大佬，许可证没有写上你的大名

### ISSUE THREAD

**Issue by HolyshitOvO** [ghmxr/apkextractor#7]
第635行：Copyright (C) \<year\>  \<name of author\>
第655行：\<program\>  Copyright (C) \<year\>  \<name of author\>

**Comment by ghmxr** [comment]
> 第635行：Copyright (C) <year> <name of author> 第655行：<program> Copyright (C) <year> <name of author>

感谢指正，下次提交更新时改掉

**Comment by Reza478** [comment]
I can not export obb and data in Apk Kit with android 11 can you help me

**Comment by ghmxr** [comment]
> I can not export obb and data in Apk Kit with android 11 can you help me

try Build 15
